/**
 * Ambient declarations for `apps/web`.
 *
 * Why this file exists:
 * Next.js auto-generates `next-env.d.ts` only after the first `next dev` or
 * `next build`. In CI's fresh checkout, that file doesn't exist yet when
 * `tsc --noEmit` runs in the `web-lint-and-typecheck` lane, which causes
 * `import './globals.css'` to fail with TS2882. Committing the autogenerated
 * `next-env.d.ts` is the alternative but goes against Next's own convention
 * (it's in their default `.gitignore`).
 *
 * This minimal ambient file only declares what tsc needs without coupling to
 * Next's autogenerated content.
 */

// Side-effect CSS imports (Next handles them via its bundler).
declare module '*.css';
