version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: matchday-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matchday_social
    ports:
      - '5432:5432'
    volumes:
      - matchday_pgdata:/var/lib/postgresql/data

volumes:
  matchday_pgdata:
